POST http://localhost:5000/api/v1/superheroes/superhero HTTP/1.1
Content-Type: application/json

{
  "superhero__name": "Batman",
  "real_name": "Bruce Wayne",
  "features":[{
    "universe": "DC",
    "superpowers": ["Money", "Charisma"],
    "sidekick": [{
      "sidekick_name": "Robin",
      "powers": ["Parkour"]
    }]
  }]
}

###
GET http://localhost:5000/api/v1/superheroes HTTP/1.1
Content-Type: application/json

###
GET http://localhost:5000/api/v1/superheroes/6231388dea18c086f54c6917 HTTP/1.1

###
PUT http://localhost:5000/api/v1/superheroes/6231321b06a2c091508e881a HTTP/1.1
Content-Type: application/json

{
  "superhero__name": "Batman",
  "real_name": "Bruce Wayne",
  "features":[{
    "universe": "DC",
    "superpowers": ["Money", "Charisma"],
    "sidekick": [{
      "sidekick_name": "Catwoman",
      "powers": ["Parkour"]
    }]
  }]
}

###
DELETE http://localhost:5000/api/v1/superheroes/6231321b06a2c091508e881a HTTP/1.1
Content-Type: application/json

###
GET http://localhost:5000/api/v1/superheroes/sidekickPowers/6231388dea18c086f54c6917 HTTP/1.1
Content-Type: application/json

###
POST http://localhost:5000/api/v1/superheroes_v2/superhero HTTP/1.1
Content-Type: application/json

{
  "superhero":"Batman2",
  "real_name":"Bruce Wayne",
  "super_power":"Money"
}